version: '3.8'

services:
  portfolio-website:
    build: ./PortfolioWebsite
    ports:
      - "3000:3000"
  aiden:
    build: ./SoftwareAssistant
    ports:
      - "5000:5000"
    env_file:
      - .env
