services:
  reverse-proxy:
    build: ./Nginx
    ports:
      - "80:8080"
      - "8082:8082"
    volumes:
      - ./Nginx/logs:/var/log/nginx
    depends_on:
      - portfolio-website
      - aiden
      - matomo
      - db


  portfolio-website:
    build: ./PortfolioWebsite
    environment:
      - NEXT_PUBLIC_MATOMO_URL="http://localhost:8000"
      - NEXT_PUBLIC_MATOMO_SITE_ID="1"
    depends_on:
      - matomo


  ollama-embedding:
    build: ./Ollama/Embeddings
    volumes:
      - ollama-embedding:/root/.ollama


  ollama-query:
    build: ./Ollama/Query
    image: ollama/ollama:latest
    volumes:
      - ollama-query:/root/.ollama


  aiden:
    build: ./SoftwareAssistant
    env_file:
      - .env
    depends_on:
      - ollama-embedding
      - db


  matomo:
    image: matomo
    volumes:
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --max-allowed-packet=64MB
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/mysql

volumes:
  matomo:
  db:
  ollama-embedding:
  ollama-query: